services:
  - type: web
    name: fitscore-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    rootDir: ml-backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12